SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE Lab;
USE Lab;
CREATE TABLE MUNICIPIOS(
    id INT NOT NULL AUTO_INCREMENT,
    nombre varchar(40) NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE VIVIENDAS(
    id INT NOT NULL  AUTO_INCREMENT,
    direccion varchar(40) NOT NULL,
    id_municipio int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_municipio) REFERENCES MUNICIPIOS(id)
);

CREATE TABLE PERSONAS(
    id INT NOT NULL  AUTO_INCREMENT,
    nombre varchar(40) NOT NULL,
    edad int NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE CABEZA_DE_FAMILIA(
    id INT NOT NULL  AUTO_INCREMENT,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES PERSONAS(id)
);

CREATE TABLE DEPENDIENTES(
    id INT NOT NULL ,
    id_cabeza INT NOT NULL,
    FOREIGN KEY (id) REFERENCES PERSONAS(id),
    FOREIGN KEY (id_cabeza) REFERENCES CABEZA_DE_FAMILIA(id)
);

CREATE TABLE HABITANTE_VIVIENDA(
    id_habitante INT NOT NULL,
    id_vivienda INT NOT NULL,
    FOREIGN KEY (id_habitante) REFERENCES PERSONAS(id),
    FOREIGN KEY (id_vivienda) REFERENCES VIVIENDAS(id)
);

CREATE TABLE VIVIENDAS_PROPIETARIOS(
    id_vivienda INT NOT NULL,
    id_poseedor INT NOT NULL,
    FOREIGN KEY (id_vivienda) REFERENCES VIVIENDAS(id),
    FOREIGN KEY (id_poseedor) REFERENCES PERSONAS(id)
);
